export const Permission = {
  TasksRead: 'tasks.read',
  TasksCreate: 'tasks.create',
  TasksManage: 'tasks.manage',
  CalendarRead: 'calendar.read',
  CalendarManage: 'calendar.manage',
  DocumentsRead: 'documents.read',
  DocumentsManage: 'documents.manage',
  KnowledgeRead: 'knowledge.read',
  KnowledgeManage: 'knowledge.manage',
  EmployeesRead: 'employees.read',
  LifecycleManage: 'lifecycle.manage',
  AnnouncementsRead: 'announcements.read',
  AnnouncementsCreate: 'announcements.create',
  AnnouncementsPublish: 'announcements.publish',
  AnalyticsRead: 'analytics.read',
  MessagesRead: 'messages.read',
  MessagesWrite: 'messages.write',
  MessagesManage: 'messages.manage',
  NotificationsRead: 'notifications.read',
  FeedRead: 'feed.read',
  FeedCreate: 'feed.create',
  FeedModerate: 'feed.moderate',
  GroupsRead: 'groups.read',
  GroupsCreate: 'groups.create',
  GroupsManage: 'groups.manage',
  GroupsMembersManage: 'groups.members.manage',
  CallsRead: 'calls.read',
  CallsCreate: 'calls.create',
  CallsManage: 'calls.manage',
  EmployeesOrgRead: 'employees.org.read',
  AbsencesReadSelf: 'absences.read.self',
  AbsencesReadOrganization: 'absences.read.company',
  AbsencesManage: 'absences.manage',
  DocumentsShare: 'documents.share',
  UsersManage: 'users.manage',
  UsersCredentialsReset: 'users.credentials.reset',
  UsersMfaReset: 'users.mfa.reset',
  UsersSecurityUnlock: 'users.security.unlock',
  RolesManage: 'roles.manage',
  OrganizationManage: 'companies.manage',
  SecurityManage: 'security.manage',
  AuditRead: 'audit.read',
  AuditExport: 'audit.export',
  SystemManage: 'system.manage',
  ConfidentialHrRead: 'confidential.hr.read',
  ConfidentialSecurityRead: 'confidential.security.read',
} as const

export type PermissionCode = (typeof Permission)[keyof typeof Permission]

export const allPermissionCodes = Object.values(Permission)
