import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import Database from 'better-sqlite3'
import { mkdirSync, readFileSync, rmSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

const testDb = resolve('test/tmp/migrations.db')
let openDatabase: InstanceType<typeof Database> | undefined

beforeEach(() => rmSync(dirname(testDb), { recursive: true, force: true }))

afterEach(() => {
  openDatabase?.close()
  openDatabase = undefined
  rmSync(dirname(testDb), { recursive: true, force: true })
})

describe('ordered SQLite migrations', () => {
  it('create an append-only audit table and FTS5 index from an empty database', () => {
    mkdirSync(dirname(testDb), { recursive: true })
    const db = new Database(testDb)
    openDatabase = db
    const init = readFileSync(resolve('prisma/migrations/20260715112458_init/migration.sql'), 'utf8')
    const guards = readFileSync(resolve('prisma/migrations/20260715113000_platform_guards/migration.sql'), 'utf8')
    const keyVersion = readFileSync(resolve('prisma/migrations/20260715130000_private_key_version/migration.sql'), 'utf8')
    const capabilities = readFileSync(resolve('prisma/migrations/20260722180000_company_capabilities/migration.sql'), 'utf8')
    const groupOrgKernel = readFileSync(resolve('prisma/migrations/20260722193000_group_org_kernel/migration.sql'), 'utf8')
    const importControlPlane = readFileSync(resolve('prisma/migrations/20260723113000_import_control_plane/migration.sql'), 'utf8')
    const feedKernel = readFileSync(resolve('prisma/migrations/20260723150000_feed_kernel/migration.sql'), 'utf8')
    const feedSourceProjections = readFileSync(resolve('prisma/migrations/20260723173000_feed_source_projections/migration.sql'), 'utf8')
    const feedFavorites = readFileSync(resolve('prisma/migrations/20260723193000_feed_favorites/migration.sql'), 'utf8')
    const feedFileShares = readFileSync(resolve('prisma/migrations/20260723211500_feed_file_shares/migration.sql'), 'utf8')
    const feedSourceHeads = readFileSync(resolve('prisma/migrations/20260723223000_feed_source_heads/migration.sql'), 'utf8')
    const feedSourceHeadUnread = readFileSync(resolve('prisma/migrations/20260723224500_feed_source_head_unread/migration.sql'), 'utf8')
    const taskHierarchy = readFileSync(resolve('prisma/migrations/20260724090000_task_hierarchy/migration.sql'), 'utf8')
    const taskParticipants = readFileSync(resolve('prisma/migrations/20260724120000_task_participants/migration.sql'), 'utf8')
    const taskPersonalWorkflow = readFileSync(resolve('prisma/migrations/20260724150000_task_personal_workflow/migration.sql'), 'utf8')
    const taskContentContext = readFileSync(resolve('prisma/migrations/20260724180000_task_content_context/migration.sql'), 'utf8')
    const chatCore = readFileSync(resolve('prisma/migrations/20260724210000_chat_core/migration.sql'), 'utf8')
    const chatCollaboration = readFileSync(resolve('prisma/migrations/20260724233000_chat_collaboration/migration.sql'), 'utf8')
    const chatMessageConversions = readFileSync(resolve('prisma/migrations/20260725090000_chat_message_conversions/migration.sql'), 'utf8')
    db.exec(init)
    db.exec(guards)
    db.exec(keyVersion)
    db.exec(capabilities)
    db.exec(groupOrgKernel)
    db.exec(importControlPlane)
    db.exec(feedKernel)
    db.exec(feedSourceProjections)
    db.exec(feedFavorites)
    db.exec(feedFileShares)
    db.exec(feedSourceHeads)
    db.exec(feedSourceHeadUnread)
    db.exec(taskHierarchy)
    db.exec(taskParticipants)
    db.exec(taskPersonalWorkflow)
    db.exec(taskContentContext)
    db.exec(chatCore)
    db.exec(chatCollaboration)
    db.exec(chatMessageConversions)
    expect(db.prepare("SELECT name FROM pragma_table_info('RequestPrivateDetail') WHERE name = 'keyVersion'").get()).toEqual({ name: 'keyVersion' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'CompanyCapability'").get()).toEqual({ name: 'CompanyCapability' })
    expect(db.prepare("SELECT code FROM Permission WHERE code = 'feed.read'").get()).toEqual({ code: 'feed.read' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'Group'").get()).toEqual({ name: 'Group' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'OrgUnit'").get()).toEqual({ name: 'OrgUnit' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'index' AND name = 'GroupMember_one_active_owner_key'").get()).toEqual({ name: 'GroupMember_one_active_owner_key' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'index' AND name = 'UserOrgAssignment_one_active_primary_key'").get()).toEqual({ name: 'UserOrgAssignment_one_active_primary_key' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'OrgUnit_cycle_guard_update'").get()).toEqual({ name: 'OrgUnit_cycle_guard_update' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'UserOrgAssignment_scope_guard_insert'").get()).toEqual({ name: 'UserOrgAssignment_scope_guard_insert' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'ImportDataset'").get()).toEqual({ name: 'ImportDataset' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'MigrationActivation'").get()).toEqual({ name: 'MigrationActivation' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'ImportDataset_sealed_immutable_update'").get()).toEqual({ name: 'ImportDataset_sealed_immutable_update' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'ImportChangeJournal_append_only_update'").get()).toEqual({ name: 'ImportChangeJournal_append_only_update' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'FeedPost'").get()).toEqual({ name: 'FeedPost' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'FeedItem'").get()).toEqual({ name: 'FeedItem' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'FeedItemRecipient'").get()).toEqual({ name: 'FeedItemRecipient' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'FeedUserItemState'").get()).toEqual({ name: 'FeedUserItemState' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'FeedFileShare'").get()).toEqual({ name: 'FeedFileShare' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'FeedSourceHead'").get()).toEqual({ name: 'FeedSourceHead' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'index' AND name = 'FeedSourceHead_workspaceId_companyId_occurredAt_itemId_idx'").get()).toEqual({ name: 'FeedSourceHead_workspaceId_companyId_occurredAt_itemId_idx' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'index' AND name = 'FeedSourceHead_workspaceId_companyId_countsAsUnread_occurredAt_itemId_idx'").get()).toEqual({ name: 'FeedSourceHead_workspaceId_companyId_countsAsUnread_occurredAt_itemId_idx' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'FeedSourceHead_scope_guard_update'").get()).toEqual({ name: 'FeedSourceHead_scope_guard_update' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'FeedItem_file_share_guard_insert'").get()).toEqual({ name: 'FeedItem_file_share_guard_insert' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'FeedItem_append_only_update'").get()).toEqual({ name: 'FeedItem_append_only_update' })
    expect(db.prepare("SELECT name FROM pragma_table_info('Comment') WHERE name = 'replyToCommentId'").get()).toEqual({ name: 'replyToCommentId' })
    expect(db.prepare("SELECT name FROM pragma_table_info('Task') WHERE name = 'parentTaskId'").get()).toEqual({ name: 'parentTaskId' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'index' AND name = 'Task_parentTaskId_status_deadline_id_idx'").get()).toEqual({ name: 'Task_parentTaskId_status_deadline_id_idx' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'Task_active_subtasks_completion_guard'").get()).toEqual({ name: 'Task_active_subtasks_completion_guard' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'TaskParticipant'").get()).toEqual({ name: 'TaskParticipant' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'index' AND name = 'TaskParticipant_active_role_key'").get()).toEqual({ name: 'TaskParticipant_active_role_key' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'TaskParticipant_scope_guard_insert'").get()).toEqual({ name: 'TaskParticipant_scope_guard_insert' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'TaskFollower'").get()).toEqual({ name: 'TaskFollower' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'TaskUserState'").get()).toEqual({ name: 'TaskUserState' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'TaskReminder'").get()).toEqual({ name: 'TaskReminder' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'index' AND name = 'TaskReminder_active_time_key'").get()).toEqual({ name: 'TaskReminder_active_time_key' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'TaskReminder_status_transition_update'").get()).toEqual({ name: 'TaskReminder_status_transition_update' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'FileLink_task_scope_guard_insert'").get()).toEqual({ name: 'FileLink_task_scope_guard_insert' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'Comment_task_scope_guard_insert'").get()).toEqual({ name: 'Comment_task_scope_guard_insert' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'EntityLink_task_scope_guard_insert'").get()).toEqual({ name: 'EntityLink_task_scope_guard_insert' })
    expect(db.prepare("SELECT name FROM pragma_table_info('ThreadParticipant') WHERE name = 'notificationMode'").get()).toEqual({ name: 'notificationMode' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'index' AND name = 'MessageThread_directKey_key'").get()).toEqual({ name: 'MessageThread_directKey_key' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'Message_chat_scope_guard_insert'").get()).toEqual({ name: 'Message_chat_scope_guard_insert' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'FileLink_message_scope_guard_insert'").get()).toEqual({ name: 'FileLink_message_scope_guard_insert' })
    expect(db.prepare("SELECT name FROM sqlite_master WHERE type = 'trigger' AND name = 'EntityLink_event_message_scope_guard_insert'").get()).toEqual({ name: 'EntityLink_event_message_scope_guard_insert' })
    db.prepare('INSERT INTO AuditEvent (id, workspaceId, actorType, action, entityType, entityId, result, risk, correlationId) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)').run('aud_test', 'ws_test', 'SYSTEM', 'test.created', 'TEST', 'entity', 'SUCCESS', 'NORMAL', 'corr_test')
    expect(() => db.prepare('UPDATE AuditEvent SET result = ? WHERE id = ?').run('FAILURE', 'aud_test')).toThrow(/append[_-]only/i)
    expect(() => db.prepare('DELETE FROM AuditEvent WHERE id = ?').run('aud_test')).toThrow(/append[_-]only/i)
    db.prepare('INSERT INTO Workspace (id, displayName, updatedAt) VALUES (?, ?, CURRENT_TIMESTAMP)').run('ws_import', 'Import QA')
    db.prepare('INSERT INTO Company (id, workspaceId, displayName, legalName, code, updatedAt) VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)').run('cmp_import', 'ws_import', 'Import QA', 'Import QA LLC', 'IQA')
    db.prepare("INSERT INTO User (id, workspaceId, primaryCompanyId, displayName, username, normalizedUsername, displayRole, status, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, 'ACTIVE', CURRENT_TIMESTAMP)").run('usr_import', 'ws_import', 'cmp_import', 'Import Admin', 'import.admin', 'import.admin', 'Administrator')
    db.prepare('INSERT INTO UserCompanyAccess (id, userId, companyId) VALUES (?, ?, ?)').run('uca_import', 'usr_import', 'cmp_import')
    db.prepare('INSERT INTO SourceCompanyMapping (id, workspaceId, sourceSystem, sourceTenantId, version, sourceOrgUnitKey, targetCompanyId, status, createdById, activatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)').run('scm_import', 'ws_import', 'bitrix24', 'portal.example', 1, 'root', 'cmp_import', 'ACTIVE', 'usr_import')
    expect(() => db.prepare("INSERT INTO ImportDataset (id, workspaceId, sourceSystem, sourceTenantId, sourceBuild, sourceSchemaFingerprint, companyMappingVersion, kind, sequence, exportedAt, watermarkToJson, mappingVersion, schemaVersion, manifestSha256, encryptionKeyId, status, sealedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, '{}', ?, ?, ?, ?, 'SEALED', CURRENT_TIMESTAMP)").run('dataset_direct_sealed', 'ws_import', 'bitrix24', 'portal.example', '24.0', 'schema-v1', 1, 'SNAPSHOT', 10, 1, 1, 'd'.repeat(64), 'key-1')).toThrow(/start[_-]ingesting/i)
    db.prepare("INSERT INTO ImportDataset (id, workspaceId, sourceSystem, sourceTenantId, sourceBuild, sourceSchemaFingerprint, companyMappingVersion, kind, sequence, exportedAt, watermarkToJson, mappingVersion, schemaVersion, manifestSha256, encryptionKeyId) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, '{}', ?, ?, ?, ?)").run('dataset_import', 'ws_import', 'bitrix24', 'portal.example', '24.0', 'schema-v1', 1, 'SNAPSHOT', 0, 1, 1, 'a'.repeat(64), 'key-1')
    db.prepare("INSERT INTO ImportFile (id, datasetId, sourceType, safeFilename, bytes, sha256, recordCount, status, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)").run('file_import', 'dataset_import', 'users', 'users.ndjson', 100, 'b'.repeat(64), 1, 'VERIFIED')
    db.prepare("UPDATE ImportDataset SET status = 'SEALED', sealedAt = CURRENT_TIMESTAMP WHERE id = ?").run('dataset_import')
    expect(() => db.prepare("UPDATE ImportDataset SET watermarkToJson = '{\"changed\":true}' WHERE id = ?").run('dataset_import')).toThrow(/sealed[_-]immutable/i)
    expect(() => db.prepare("INSERT INTO ImportDataset (id, workspaceId, sourceSystem, sourceTenantId, sourceBuild, sourceSchemaFingerprint, companyMappingVersion, kind, parentDatasetId, sequence, exportedAt, watermarkFromJson, watermarkToJson, mappingVersion, schemaVersion, manifestSha256, encryptionKeyId) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, '{}', '{}', ?, ?, ?, ?)").run('delta_import', 'ws_import', 'bitrix24', 'portal.example', '24.0', 'schema-v1', 1, 'DELTA', 'dataset_import', 2, 1, 1, 'c'.repeat(64), 'key-1')).toThrow(/chain[_-]mismatch/i)
    expect(() => db.prepare("INSERT INTO ImportRun (id, datasetId, mode, status, updatedAt) VALUES (?, ?, 'APPLY', 'RUNNING', CURRENT_TIMESTAMP)").run('run_direct_running', 'dataset_import')).toThrow(/start[_-]queued/i)
    db.prepare("INSERT INTO ImportRun (id, datasetId, mode, updatedAt) VALUES (?, ?, 'APPLY', CURRENT_TIMESTAMP)").run('run_import', 'dataset_import')
    expect(() => db.prepare("UPDATE ImportRun SET status = 'RUNNING', updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('run_import')).toThrow(/lease[_-]required/i)
    db.prepare("INSERT INTO ImportChangeJournal (id, runId, operation) VALUES (?, ?, 'NOOP')").run('journal_import', 'run_import')
    expect(() => db.prepare("UPDATE ImportChangeJournal SET operation = 'UPDATE' WHERE id = ?").run('journal_import')).toThrow(/append[_-]only/i)
    expect(() => db.prepare('DELETE FROM ImportChangeJournal WHERE id = ?').run('journal_import')).toThrow(/append[_-]only/i)
    db.prepare("INSERT INTO FeedPost (id, workspaceId, companyId, authorId, body) VALUES (?, ?, ?, ?, ?)").run('feed_import', 'ws_import', 'cmp_import', 'usr_import', 'Immutable feed item')
    db.prepare("INSERT INTO FeedPostRecipient (id, postId, type, recipientId) VALUES (?, ?, 'COMPANY', ?)").run('frcp_import', 'feed_import', 'cmp_import')
    db.prepare("INSERT INTO FeedItem (id, workspaceId, companyId, postId, sourceType, sourceId, sourceVersion, action, eventKey, actorId, visibility, safePayload, occurredAt) VALUES (?, ?, ?, ?, 'POST', ?, 1, 'PUBLISHED', ?, ?, 'COMPANY', '{}', CURRENT_TIMESTAMP)").run('fitem_import', 'ws_import', 'cmp_import', 'feed_import', 'feed_import', 'feed:post:feed_import:v1:published', 'usr_import')
    db.prepare("INSERT INTO FeedSourceHead (id, workspaceId, companyId, sourceType, sourceId, itemId, sourceVersion, occurredAt) SELECT ?, workspaceId, companyId, sourceType, sourceId, id, sourceVersion, occurredAt FROM FeedItem WHERE id = ?").run('fhead_import', 'fitem_import')
    db.prepare("INSERT INTO FeedItem (id, workspaceId, companyId, postId, sourceType, sourceId, sourceVersion, action, eventKey, actorId, visibility, safePayload, occurredAt) VALUES (?, ?, ?, ?, 'POST', ?, 2, 'EDITED', ?, ?, 'COMPANY', '{}', datetime(CURRENT_TIMESTAMP, '+1 second'))").run('fitem_import_v2', 'ws_import', 'cmp_import', 'feed_import', 'feed_import', 'feed:post:feed_import:v2:edited', 'usr_import')
    db.prepare("UPDATE FeedSourceHead SET itemId = ?, sourceVersion = 2, occurredAt = (SELECT occurredAt FROM FeedItem WHERE id = ?), updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('fitem_import_v2', 'fitem_import_v2', 'fhead_import')
    expect(() => db.prepare("UPDATE FeedSourceHead SET itemId = ?, sourceVersion = 1, occurredAt = (SELECT occurredAt FROM FeedItem WHERE id = ?), updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('fitem_import', 'fitem_import', 'fhead_import')).toThrow(/head[_-]regression/i)
    db.prepare("INSERT INTO FeedItemRecipient (id, itemId, userId) VALUES (?, ?, ?)").run('firec_import', 'fitem_import', 'usr_import')
    db.prepare("INSERT INTO FeedUserItemState (id, userId, feedItemId, favoritedAt, updatedAt) VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)").run('fstate_import', 'usr_import', 'fitem_import')
    db.prepare("INSERT INTO User (id, workspaceId, primaryCompanyId, displayName, username, normalizedUsername, displayRole, status, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, 'ACTIVE', CURRENT_TIMESTAMP)").run('usr_without_access', 'ws_import', 'cmp_import', 'No Access', 'no.access', 'no.access', 'Employee')
    db.prepare("INSERT INTO Task (id, workspaceId, companyId, number, title, creatorId, assigneeId, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)").run('task_parent', 'ws_import', 'cmp_import', 'TSK-PARENT', 'Parent task', 'usr_import', 'usr_import')
    db.prepare("INSERT INTO Task (id, workspaceId, companyId, parentTaskId, number, title, creatorId, assigneeId, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)").run('task_child', 'ws_import', 'cmp_import', 'task_parent', 'TSK-CHILD', 'Child task', 'usr_import', 'usr_import')
    expect(() => db.prepare("INSERT INTO Task (id, workspaceId, companyId, parentTaskId, number, title, creatorId, assigneeId, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)").run('task_grandchild', 'ws_import', 'cmp_import', 'task_child', 'TSK-GRANDCHILD', 'Grandchild task', 'usr_import', 'usr_import')).toThrow(/subtask[_-]depth/i)
    db.prepare('INSERT INTO Company (id, workspaceId, displayName, legalName, code, updatedAt) VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)').run('cmp_import_other', 'ws_import', 'Import Other', 'Import Other LLC', 'IO')
    expect(() => db.prepare("INSERT INTO Task (id, workspaceId, companyId, parentTaskId, number, title, creatorId, assigneeId, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)").run('task_cross_company', 'ws_import', 'cmp_import_other', 'task_parent', 'TSK-CROSS', 'Cross-company child', 'usr_import', 'usr_import')).toThrow(/parent[_-]scope/i)
    expect(() => db.prepare("UPDATE Task SET status = 'DONE', updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('task_parent')).toThrow(/active[_-]subtasks/i)
    db.prepare("UPDATE Task SET status = 'DONE', completedAt = CURRENT_TIMESTAMP, updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('task_child')
    db.prepare("UPDATE Task SET status = 'DONE', completedAt = CURRENT_TIMESTAMP, updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('task_parent')
    expect(db.prepare('SELECT status FROM Task WHERE id = ?').get('task_parent')).toEqual({ status: 'DONE' })
    db.prepare("INSERT INTO User (id, workspaceId, primaryCompanyId, displayName, username, normalizedUsername, displayRole, status, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, 'ACTIVE', CURRENT_TIMESTAMP)").run('usr_task_participant', 'ws_import', 'cmp_import', 'Task Participant', 'task.participant', 'task.participant', 'Employee')
    db.prepare('INSERT INTO UserCompanyAccess (id, userId, companyId) VALUES (?, ?, ?)').run('uca_task_participant', 'usr_task_participant', 'cmp_import')
    db.prepare("INSERT INTO Task (id, workspaceId, companyId, number, title, creatorId, assigneeId, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)").run('task_with_participant', 'ws_import', 'cmp_import', 'TSK-PART', 'Task with participants', 'usr_import', 'usr_import')
    db.prepare("INSERT INTO TaskParticipant (id, taskId, userId, role, addedById) VALUES (?, ?, ?, 'CO_EXECUTOR', ?)").run('tpart_valid', 'task_with_participant', 'usr_task_participant', 'usr_import')
    expect(() => db.prepare("INSERT INTO TaskParticipant (id, taskId, userId, role, addedById) VALUES (?, ?, ?, 'CO_EXECUTOR', ?)").run('tpart_duplicate', 'task_with_participant', 'usr_task_participant', 'usr_import')).toThrow(/unique/i)
    expect(() => db.prepare("INSERT INTO TaskParticipant (id, taskId, userId, role, addedById) VALUES (?, ?, ?, 'OBSERVER', ?)").run('tpart_no_access', 'task_with_participant', 'usr_without_access', 'usr_import')).toThrow(/participant[_-]scope/i)
    expect(() => db.prepare("UPDATE TaskParticipant SET role = 'OBSERVER' WHERE id = ?").run('tpart_valid')).toThrow(/participant[_-]immutable/i)
    db.prepare("UPDATE TaskParticipant SET removedAt = CURRENT_TIMESTAMP WHERE id = ?").run('tpart_valid')
    expect(() => db.prepare("UPDATE TaskParticipant SET removedAt = NULL WHERE id = ?").run('tpart_valid')).toThrow(/removal[_-]immutable/i)
    db.prepare("INSERT INTO TaskParticipant (id, taskId, userId, role, addedById) VALUES (?, ?, ?, 'CO_EXECUTOR', ?)").run('tpart_readded', 'task_with_participant', 'usr_task_participant', 'usr_import')
    expect(() => db.prepare("UPDATE Task SET companyId = ?, updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('cmp_import_other', 'task_with_participant')).toThrow(/participant[_-]scope[_-]immutable/i)
    db.prepare("INSERT INTO \"Group\" (id, workspaceId, companyId, key, name, ownerId, updatedAt) VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)").run('grp_task_participant', 'ws_import', 'cmp_import', 'task-participant-group', 'Task participant group', 'usr_import')
    db.prepare("INSERT INTO Task (id, workspaceId, companyId, groupId, number, title, creatorId, assigneeId, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)").run('task_group_participant', 'ws_import', 'cmp_import', 'grp_task_participant', 'TSK-GPART', 'Group participant task', 'usr_import', 'usr_import')
    expect(() => db.prepare("INSERT INTO TaskParticipant (id, taskId, userId, role, addedById) VALUES (?, ?, ?, 'OBSERVER', ?)").run('tpart_group_denied', 'task_group_participant', 'usr_task_participant', 'usr_import')).toThrow(/participant[_-]group/i)
    expect(db.prepare("SELECT COUNT(*) AS count FROM TaskParticipant WHERE taskId = ? AND removedAt IS NULL").get('task_with_participant')).toEqual({ count: 1 })
    db.prepare("INSERT INTO Task (id, workspaceId, companyId, number, title, creatorId, assigneeId, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)").run('task_personal', 'ws_import', 'cmp_import', 'TSK-PERSONAL', 'Personal workflow task', 'usr_import', 'usr_task_participant')
    db.prepare("INSERT INTO TaskFollower (id, taskId, userId) VALUES (?, ?, ?)").run('tfol_valid', 'task_personal', 'usr_task_participant')
    expect(() => db.prepare("INSERT INTO TaskFollower (id, taskId, userId) VALUES (?, ?, ?)").run('tfol_duplicate', 'task_personal', 'usr_task_participant')).toThrow(/unique/i)
    expect(() => db.prepare("INSERT INTO TaskFollower (id, taskId, userId) VALUES (?, ?, ?)").run('tfol_denied', 'task_personal', 'usr_without_access')).toThrow(/follower[_-]scope/i)
    expect(() => db.prepare("UPDATE TaskFollower SET userId = ? WHERE id = ?").run('usr_import', 'tfol_valid')).toThrow(/follower[_-]immutable/i)
    db.prepare("INSERT INTO TaskUserState (id, taskId, userId, favoritedAt, important, updatedAt) VALUES (?, ?, ?, CURRENT_TIMESTAMP, true, CURRENT_TIMESTAMP)").run('tstate_valid', 'task_personal', 'usr_task_participant')
    db.prepare("UPDATE TaskUserState SET important = false, updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('tstate_valid')
    expect(() => db.prepare("INSERT INTO TaskUserState (id, taskId, userId, updatedAt) VALUES (?, ?, ?, CURRENT_TIMESTAMP)").run('tstate_denied', 'task_personal', 'usr_without_access')).toThrow(/user[_-]state[_-]scope/i)
    const reminderTime = '2030-01-02T09:00:00.000Z'
    db.prepare("INSERT INTO TaskReminder (id, taskId, userId, remindAt, updatedAt) VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)").run('trm_valid', 'task_personal', 'usr_task_participant', reminderTime)
    expect(() => db.prepare("INSERT INTO TaskReminder (id, taskId, userId, remindAt, updatedAt) VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)").run('trm_duplicate', 'task_personal', 'usr_task_participant', reminderTime)).toThrow(/unique/i)
    expect(() => db.prepare("INSERT INTO TaskReminder (id, taskId, userId, remindAt, updatedAt) VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)").run('trm_denied', 'task_personal', 'usr_without_access', reminderTime)).toThrow(/reminder[_-]scope/i)
    expect(() => db.prepare("UPDATE TaskReminder SET remindAt = datetime(remindAt, '+1 day'), updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('trm_valid')).toThrow(/reminder[_-]immutable/i)
    db.prepare("UPDATE TaskReminder SET status = 'SENT', updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('trm_valid')
    expect(() => db.prepare("UPDATE TaskReminder SET status = 'ACTIVE', updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('trm_valid')).toThrow(/reminder[_-]invalid[_-]transition/i)
    expect(() => db.prepare("UPDATE Task SET companyId = ?, updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('cmp_import_other', 'task_personal')).toThrow(/personal[_-]scope[_-]immutable/i)
    db.prepare("INSERT INTO Task (id, workspaceId, companyId, number, title, creatorId, assigneeId, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)").run('task_content', 'ws_import', 'cmp_import', 'TSK-CONTENT', 'Task content context', 'usr_import', 'usr_task_participant')
    db.prepare("INSERT INTO FileObject (id, workspaceId, companyId, storageKey, safeFilename, declaredMime, detectedMime, bytes, sha256, scanStatus, ownerId, updatedAt) VALUES (?, ?, ?, ?, ?, 'text/plain', 'text/plain', 12, ?, 'CLEAN', ?, CURRENT_TIMESTAMP)").run('file_task_content', 'ws_import', 'cmp_import', 'cmp_import/file_task_content', 'task-note.txt', 'c'.repeat(64), 'usr_task_participant')
    db.prepare("INSERT INTO FileLink (id, fileId, entityType, entityId, purpose, aclMode) VALUES (?, ?, 'TASK', ?, 'ATTACHMENT', 'ENTITY')").run('flink_task_content', 'file_task_content', 'task_content')
    expect(() => db.prepare("INSERT INTO FileLink (id, fileId, entityType, entityId, purpose, aclMode) VALUES (?, ?, 'TASK', ?, 'PREVIEW', 'ENTITY')").run('flink_task_bad_policy', 'file_task_content', 'task_content')).toThrow(/policy[_-]mismatch/i)
    db.prepare("INSERT INTO Comment (id, workspaceId, companyId, entityType, entityId, authorId, body, visibility) VALUES (?, ?, ?, 'TASK', ?, ?, ?, 'PARTICIPANTS')").run('cmt_task_parent', 'ws_import', 'cmp_import', 'task_content', 'usr_task_participant', 'Parent comment')
    db.prepare("INSERT INTO Comment (id, workspaceId, companyId, entityType, entityId, authorId, body, visibility, replyToCommentId) VALUES (?, ?, ?, 'TASK', ?, ?, ?, 'PARTICIPANTS', ?)").run('cmt_task_reply', 'ws_import', 'cmp_import', 'task_content', 'usr_import', 'Valid reply', 'cmt_task_parent')
    expect(() => db.prepare("INSERT INTO Comment (id, workspaceId, companyId, entityType, entityId, authorId, body, visibility, replyToCommentId) VALUES (?, ?, ?, 'TASK', ?, ?, ?, 'PARTICIPANTS', ?)").run('cmt_task_nested', 'ws_import', 'cmp_import', 'task_content', 'usr_import', 'Nested reply', 'cmt_task_reply')).toThrow(/reply[_-]mismatch/i)
    expect(() => db.prepare("INSERT INTO Comment (id, workspaceId, companyId, entityType, entityId, authorId, body, visibility) VALUES (?, ?, ?, 'TASK', ?, ?, ?, 'PARTICIPANTS')").run('cmt_task_denied', 'ws_import', 'cmp_import', 'task_content', 'usr_without_access', 'Denied comment')).toThrow(/comment[_-]scope/i)
    db.prepare("INSERT INTO FileLink (id, fileId, entityType, entityId, purpose, aclMode) VALUES (?, ?, 'TASK_COMMENT', ?, 'ATTACHMENT', 'ENTITY')").run('flink_task_comment', 'file_task_content', 'cmt_task_reply')
    expect(() => db.prepare("UPDATE FileLink SET purpose = 'PREVIEW' WHERE id = ?").run('flink_task_content')).toThrow(/file[_-]link[_-]immutable/i)
    db.prepare("INSERT INTO MessageThread (id, workspaceId, companyId, kind, title, createdById) VALUES (?, ?, ?, 'CONTEXTUAL', ?, ?)").run('thread_task_content', 'ws_import', 'cmp_import', 'Task source', 'usr_import')
    db.prepare("INSERT INTO ThreadParticipant (id, threadId, userId, role) VALUES (?, ?, ?, 'MEMBER')").run('thread_participant_task_content', 'thread_task_content', 'usr_import')
    db.prepare("INSERT INTO Message (id, threadId, authorId, body) VALUES (?, ?, ?, ?)").run('message_task_content', 'thread_task_content', 'usr_import', 'Create task from this')
    db.prepare("INSERT INTO EntityLink (id, sourceType, sourceId, targetType, targetId, relation, createdBy) VALUES (?, 'TASK', ?, 'MESSAGE', ?, 'RELATED', ?)").run('elink_task_message', 'task_content', 'message_task_content', 'usr_import')
    expect(() => db.prepare("UPDATE EntityLink SET relation = 'STEP' WHERE id = ?").run('elink_task_message')).toThrow(/entity[_-]link[_-]immutable/i)
    expect(() => db.prepare("UPDATE Task SET companyId = ?, updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('cmp_import_other', 'task_content')).toThrow(/content[_-]scope[_-]immutable/i)
    db.prepare("INSERT INTO MessageThread (id, workspaceId, companyId, kind, directKey, createdById) VALUES (?, ?, ?, 'DIRECT', ?, ?)").run('thread_chat_guarded', 'ws_import', 'cmp_import', 'd'.repeat(64), 'usr_import')
    db.prepare("INSERT INTO ThreadParticipant (id, threadId, userId, role) VALUES (?, ?, ?, 'MEMBER')").run('thread_chat_owner', 'thread_chat_guarded', 'usr_import')
    db.prepare("INSERT INTO ThreadParticipant (id, threadId, userId, role) VALUES (?, ?, ?, 'MEMBER')").run('thread_chat_member', 'thread_chat_guarded', 'usr_task_participant')
    expect(() => db.prepare("INSERT INTO ThreadParticipant (id, threadId, userId, role) VALUES (?, ?, ?, 'MEMBER')").run('thread_chat_third', 'thread_chat_guarded', 'usr_without_access')).toThrow(/participant[_-](scope|limit)/i)
    db.prepare("INSERT INTO Message (id, threadId, authorId, body, createdAt) VALUES (?, ?, ?, ?, ?)").run('message_chat_root', 'thread_chat_guarded', 'usr_import', 'Root chat message', '2026-07-24T09:00:00.000Z')
    db.prepare("INSERT INTO Message (id, threadId, authorId, body, replyToId, createdAt) VALUES (?, ?, ?, ?, ?, ?)").run('message_chat_reply', 'thread_chat_guarded', 'usr_task_participant', 'Chat reply', 'message_chat_root', '2026-07-24T09:00:01.000Z')
    expect(() => db.prepare("INSERT INTO Message (id, threadId, authorId, body, replyToId, createdAt) VALUES (?, ?, ?, ?, ?, ?)").run('message_chat_nested', 'thread_chat_guarded', 'usr_import', 'Nested reply', 'message_chat_reply', '2026-07-24T09:00:02.000Z')).toThrow(/reply[_-]mismatch/i)
    expect(() => db.prepare("INSERT INTO Message (id, threadId, authorId, body) VALUES (?, ?, ?, ?)").run('message_chat_outsider', 'thread_chat_guarded', 'usr_without_access', 'Denied')).toThrow(/author[_-]scope/i)
    db.prepare("UPDATE ThreadParticipant SET notificationMode = 'NONE', version = 2 WHERE id = ?").run('thread_chat_owner')
    db.prepare("UPDATE ThreadParticipant SET lastReadMessageId = ?, version = 3 WHERE id = ?").run('message_chat_root', 'thread_chat_owner')
    db.prepare("UPDATE ThreadParticipant SET lastReadMessageId = ?, version = 4 WHERE id = ?").run('message_chat_reply', 'thread_chat_owner')
    expect(() => db.prepare("UPDATE ThreadParticipant SET lastReadMessageId = ?, version = 5 WHERE id = ?").run('message_chat_root', 'thread_chat_owner')).toThrow(/read[_-]pointer[_-]regression/i)
    expect(() => db.prepare("UPDATE ThreadParticipant SET leftAt = CURRENT_TIMESTAMP, version = 2 WHERE id = ?").run('thread_chat_member')).toThrow(/membership[_-]immutable/i)
    db.prepare("INSERT INTO FileObject (id, workspaceId, companyId, storageKey, safeFilename, declaredMime, detectedMime, bytes, sha256, scanStatus, ownerId, updatedAt) VALUES (?, ?, ?, ?, ?, 'text/plain', 'text/plain', 12, ?, 'CLEAN', ?, CURRENT_TIMESTAMP)").run('file_chat_message', 'ws_import', 'cmp_import', 'cmp_import/file_chat_message', 'chat-note.txt', 'e'.repeat(64), 'usr_import')
    db.prepare("INSERT INTO FileLink (id, fileId, entityType, entityId, purpose, aclMode) VALUES (?, ?, 'MESSAGE', ?, 'ATTACHMENT', 'ENTITY')").run('flink_chat_message', 'file_chat_message', 'message_chat_root')
    expect(() => db.prepare("UPDATE FileLink SET purpose = 'PREVIEW' WHERE id = ?").run('flink_chat_message')).toThrow(/file[_-]link[_-]immutable/i)
    db.prepare("UPDATE Message SET body = ?, editedAt = CURRENT_TIMESTAMP, version = 2 WHERE id = ?").run('Edited root chat message', 'message_chat_root')
    db.prepare("INSERT INTO Event (id, workspaceId, companyId, ownerId, title, startAt, endAt, sourceTimezone, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)").run('event_chat_root', 'ws_import', 'cmp_import', 'usr_import', 'Chat event', '2026-07-25T09:00:00.000Z', '2026-07-25T10:00:00.000Z', 'Europe/Kyiv')
    db.prepare("INSERT INTO EntityLink (id, sourceType, sourceId, targetType, targetId, relation, createdBy) VALUES (?, 'EVENT', ?, 'MESSAGE', ?, 'RELATED', ?)").run('elink_event_message', 'event_chat_root', 'message_chat_root', 'usr_import')
    expect(() => db.prepare("UPDATE EntityLink SET relation = 'STEP' WHERE id = ?").run('elink_event_message')).toThrow(/event[_-]message[_-]link[_-]immutable/i)
    db.prepare("INSERT INTO Event (id, workspaceId, companyId, ownerId, title, startAt, endAt, sourceTimezone, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)").run('event_chat_other', 'ws_import', 'cmp_import_other', 'usr_import', 'Wrong scope', '2026-07-25T09:00:00.000Z', '2026-07-25T10:00:00.000Z', 'Europe/Kyiv')
    expect(() => db.prepare("INSERT INTO EntityLink (id, sourceType, sourceId, targetType, targetId, relation, createdBy) VALUES (?, 'EVENT', ?, 'MESSAGE', ?, 'RELATED', ?)").run('elink_event_message_cross', 'event_chat_other', 'message_chat_root', 'usr_import')).toThrow(/event[_-]message[_-]link[_-]scope/i)
    db.prepare("UPDATE Message SET deletedAt = CURRENT_TIMESTAMP, version = 2 WHERE id = ?").run('message_chat_reply')
    expect(() => db.prepare("UPDATE Message SET body = ?, editedAt = CURRENT_TIMESTAMP, version = 3 WHERE id = ?").run('Cannot restore', 'message_chat_reply')).toThrow(/core[_-]immutable/i)
    db.prepare("INSERT INTO User (id, workspaceId, primaryCompanyId, displayName, username, normalizedUsername, displayRole, status, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, 'ACTIVE', CURRENT_TIMESTAMP)").run('usr_chat_third', 'ws_import', 'cmp_import', 'Chat Third', 'chat.third', 'chat.third', 'Employee')
    db.prepare('INSERT INTO UserCompanyAccess (id, userId, companyId) VALUES (?, ?, ?)').run('uca_chat_third', 'usr_chat_third', 'cmp_import')
    db.prepare("INSERT INTO MessageThread (id, workspaceId, companyId, kind, title, createdById) VALUES (?, ?, ?, 'GROUP', ?, ?)").run('thread_chat_group', 'ws_import', 'cmp_import', 'Group chat', 'usr_import')
    db.prepare("INSERT INTO ThreadParticipant (id, threadId, userId, role) VALUES (?, ?, ?, 'OWNER')").run('thread_chat_group_owner', 'thread_chat_group', 'usr_import')
    db.prepare("INSERT INTO ThreadParticipant (id, threadId, userId, role) VALUES (?, ?, ?, 'MEMBER')").run('thread_chat_group_member', 'thread_chat_group', 'usr_task_participant')
    db.prepare("INSERT INTO ThreadParticipant (id, threadId, userId, role) VALUES (?, ?, ?, 'MEMBER')").run('thread_chat_group_third', 'thread_chat_group', 'usr_chat_third')
    expect(() => db.prepare("UPDATE ThreadParticipant SET role = 'MEMBER', version = 2 WHERE id = ?").run('thread_chat_group_owner')).toThrow(/owner[_-]required/i)
    db.prepare("UPDATE ThreadParticipant SET role = 'OWNER', version = 2 WHERE id = ?").run('thread_chat_group_member')
    db.prepare("UPDATE ThreadParticipant SET leftAt = CURRENT_TIMESTAMP, version = 2 WHERE id = ?").run('thread_chat_group_third')
    expect(() => db.prepare("UPDATE ThreadParticipant SET leftAt = CURRENT_TIMESTAMP, version = 3 WHERE id = ?").run('thread_chat_group_member')).toThrow(/participant[_-]minimum/i)
    expect(() => db.prepare("UPDATE MessageThread SET companyId = ? WHERE id = ?").run('cmp_import_other', 'thread_chat_guarded')).toThrow(/core[_-]immutable/i)
    expect(() => db.prepare("INSERT INTO FeedUserItemState (id, userId, feedItemId, favoritedAt, updatedAt) VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)").run('fstate_denied', 'usr_without_access', 'fitem_import')).toThrow(/scope[_-]mismatch/i)
    expect(() => db.prepare('UPDATE FeedItemRecipient SET userId = ? WHERE id = ?').run('usr_import', 'firec_import')).toThrow(/append[_-]only/i)
    expect(() => db.prepare("UPDATE FeedItem SET safePayload = '{\"changed\":true}' WHERE id = ?").run('fitem_import')).toThrow(/append[_-]only/i)
    expect(() => db.prepare('DELETE FROM FeedItem WHERE id = ?').run('fitem_import')).toThrow(/append[_-]only/i)
    db.prepare("INSERT INTO FileObject (id, workspaceId, companyId, storageKey, safeFilename, declaredMime, detectedMime, bytes, sha256, scanStatus, ownerId, updatedAt) VALUES (?, ?, ?, ?, ?, 'text/plain', 'text/plain', 12, ?, 'CLEAN', ?, CURRENT_TIMESTAMP)").run('file_shared', 'ws_import', 'cmp_import', 'cmp_import/file_shared', 'safe-note.txt', 'a'.repeat(64), 'usr_import')
    db.prepare("INSERT INTO FeedFileShare (id, workspaceId, companyId, fileId, ownerId, audienceType, audienceKey, updatedAt) VALUES (?, ?, ?, ?, ?, 'COMPANY', ?, CURRENT_TIMESTAMP)").run('fshare_import', 'ws_import', 'cmp_import', 'file_shared', 'usr_import', 'COMPANY:cmp_import')
    db.prepare("INSERT INTO FeedItem (id, workspaceId, companyId, fileShareId, sourceType, sourceId, sourceVersion, action, eventKey, actorId, visibility, safePayload, occurredAt) VALUES (?, ?, ?, ?, 'FILE', ?, 1, 'SHARED', ?, ?, 'COMPANY', '{}', CURRENT_TIMESTAMP)").run('fitem_file', 'ws_import', 'cmp_import', 'fshare_import', 'fshare_import', 'feed:file:fshare_import:v1:shared', 'usr_import')
    expect(() => db.prepare("INSERT INTO FeedItem (id, workspaceId, companyId, fileShareId, sourceType, sourceId, sourceVersion, action, eventKey, actorId, visibility, safePayload, occurredAt) VALUES (?, ?, ?, ?, 'FILE', ?, 1, 'SHARED', ?, ?, 'COMPANY', '{}', CURRENT_TIMESTAMP)").run('fitem_file_bad', 'ws_import', 'cmp_import', 'fshare_import', 'another-share', 'feed:file:bad:v1:shared', 'usr_import')).toThrow(/file[_-]share[_-]mismatch/i)
    db.prepare("UPDATE FeedFileShare SET status = 'REVOKED', version = 2, revokedAt = CURRENT_TIMESTAMP, updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('fshare_import')
    expect(() => db.prepare("UPDATE FeedFileShare SET status = 'ACTIVE', version = 3, revokedAt = NULL, updatedAt = CURRENT_TIMESTAMP WHERE id = ?").run('fshare_import')).toThrow(/invalid[_-]transition/i)
    db.prepare('INSERT INTO SearchIndex (entityType, entityId, workspaceId, companyId, title, body) VALUES (?, ?, ?, ?, ?, ?)').run('ARTICLE', 'art_test', 'ws_test', 'cmp_test', 'Політика відпусток', 'Як оформити відсутність')
    expect(db.prepare("SELECT entityId FROM SearchIndex WHERE SearchIndex MATCH 'відпусток'").get()).toEqual({ entityId: 'art_test' })
  })

  it('bounds writer contention with SQLITE_BUSY and remains writable after the lock is released', () => {
    mkdirSync(dirname(testDb), { recursive: true })
    const first = new Database(testDb)
    const second = new Database(testDb)
    openDatabase = first
    try {
      first.pragma('journal_mode = WAL')
      first.exec('CREATE TABLE BusyProbe (id TEXT PRIMARY KEY, value TEXT NOT NULL)')
      first.exec('BEGIN IMMEDIATE')
      first.prepare('INSERT INTO BusyProbe (id, value) VALUES (?, ?)').run('one', 'held')
      second.pragma('busy_timeout = 25')
      expect(() => second.prepare('INSERT INTO BusyProbe (id, value) VALUES (?, ?)').run('two', 'blocked')).toThrow(/busy|locked/i)
      first.exec('COMMIT')
      second.prepare('INSERT INTO BusyProbe (id, value) VALUES (?, ?)').run('two', 'released')
      expect(second.prepare('SELECT COUNT(*) AS count FROM BusyProbe').get()).toEqual({ count: 2 })
    } finally {
      if (first.inTransaction) first.exec('ROLLBACK')
      second.close()
    }
  })
})
