import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { DocumentListItem } from '@bert-crm/contracts'
import { BarChart3, BookOpenCheck, Building2, CalendarClock, Check, Download, File as FileIcon, FileCheck2, FilePlus2, Search, ShieldCheck, UsersRound } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { api, jsonBody } from '../shared/api/client'
import { useAuth } from '../shared/auth/AuthProvider'
import { formatDate, formatDateTime } from '../shared/lib/format'
import { Avatar, Button, Card, Drawer, EmptyState, ErrorState, PageHeader, Skeleton, StatusBadge } from '../shared/ui'

interface ArticleList { id: string; slug: string; title: string; changeSummary: string; reviewAt: string | null; version: number; updatedAt: string }
interface ArticleDetail { id: string; slug: string; version: number; reviewAt?: string | null; currentVersion: { title: string; body: string; changeSummary: string; publishedAt: string } | null; acknowledgement: { confirmedAt?: string | null } | null }
interface Employee { id: string; displayName: string; displayRole: string; jobTitle: string; primaryCompanyId: string; timezone: string; avatarAsset: string | null; presence: string; contactEmail?: string | null; approver?: { displayName: string } | null; upcomingPresence?: Array<{ state: string; startAt: string; endAt: string }> }

export default function ContentPages() {
  const path = useLocation().pathname
  if (path.startsWith('/documents')) return <DocumentsPage />
  if (path.startsWith('/knowledge')) return <KnowledgePage />
  if (path.startsWith('/employees')) return <EmployeesPage />
  return <AnalyticsPage />
}

function DocumentsPage() {
  const { documentId } = useParams(); const navigate = useNavigate(); const { can } = useAuth(); const [search, setSearch] = useState(''); const [creating, setCreating] = useState(false)
  const query = useQuery({ queryKey: ['documents', search], queryFn: () => api<{ items: DocumentListItem[] }>(`/documents?search=${encodeURIComponent(search)}`) })
  return <div><PageHeader title="Документи" description="Версійовані файли з ACL та перевіркою кожного відкриття" action={can('documents.manage') && <Button onClick={() => setCreating(true)}><FilePlus2 size={17} />Додати документ</Button>} /><Card className="list-card"><div className="list-toolbar"><label className="search-field"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Пошук документів" /></label></div>{query.isLoading ? <Skeleton rows={6} /> : query.isError ? <ErrorState onRetry={() => void query.refetch()} /> : query.data?.items.length ? <div className="responsive-table"><table><thead><tr><th>Документ</th><th>Власник</th><th>Оновлено</th><th>Статус</th></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id}><td><Link to={`/documents/${item.id}`}><span className="file-icon"><FileIcon size={18} /></span><span><strong>{item.name}</strong><small>{item.number} · {item.mimeType ?? 'файл'}</small></span></Link></td><td>{item.ownerName}</td><td>{formatDateTime(item.updatedAt)}</td><td><StatusBadge status={item.status} /></td></tr>)}</tbody></table></div> : <EmptyState title="Документів немає" description="Завантажте перший дозволений файл." />}</Card>{documentId && <DocumentDrawer id={documentId} onClose={() => navigate('/documents')} />}{creating && <DocumentCreate onClose={() => setCreating(false)} onCreated={(id) => { setCreating(false); navigate(`/documents/${id}`) }} />}</div>
}

function DocumentCreate({ onClose, onCreated }: { onClose: () => void; onCreated: (id: string) => void }) {
  const { user } = useAuth(); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget); const file = data.get('file') as globalThis.File; try { const upload = new FormData(); upload.set('file', file); const uploaded = await api<{ id: string; status: string }>(`/files?company=${user?.primaryCompanyId}`, { method: 'POST', body: upload }); let status = uploaded.status; for (let attempt = 0; attempt < 10 && status !== 'CLEAN'; attempt += 1) { await new Promise((resolve) => window.setTimeout(resolve, 600)); status = (await api<{ status: string }>(`/files/${uploaded.id}/status`)).status } if (status !== 'CLEAN') throw new Error('scan'); const document = await api<{ id: string }>('/documents', { method: 'POST', body: jsonBody({ companyId: user?.primaryCompanyId, name: data.get('name'), fileId: uploaded.id, changeSummary: data.get('summary') }) }); onCreated(document.id) } catch { setError('Файл не пройшов перевірку або документ не вдалося створити.') } finally { setBusy(false) } }
  return <Drawer title="Новий документ" onClose={onClose}><form className="entity-form" onSubmit={submit}><label className="span-2">Назва<input name="name" required maxLength={180} /></label><label className="span-2 file-input"><FilePlus2 /><span>Файл PDF, PNG, JPEG або DOCX · до 25 МБ</span><input type="file" name="file" required accept=".pdf,.png,.jpg,.jpeg,.docx" /></label><label className="span-2">Опис версії<input name="summary" placeholder="Перша версія" /></label>{error && <div className="form-error span-2">{error}</div>}<Button className="span-2" disabled={busy}>{busy ? 'Перевіряємо файл…' : 'Створити документ'}</Button></form></Drawer>
}

function DocumentDrawer({ id, onClose }: { id: string; onClose: () => void }) {
  interface Detail { id: string; number: string; name: string; status: string; version: number; confidentiality: string; versions: Array<{ id: string; fileId: string; version: number; changeSummary: string; createdAt: string; status: string }> }
  const query = useQuery({ queryKey: ['document', id], queryFn: () => api<Detail>(`/documents/${id}`) })
  const publish = useMutation({ mutationFn: () => api(`/documents/${id}/publish`, { method: 'POST', body: jsonBody({ expectedVersion: query.data?.version }) }), onSuccess: () => void query.refetch() })
  return <Drawer title={query.data?.number ?? 'Документ'} onClose={onClose} footer={query.data?.status === 'DRAFT' && <Button onClick={() => publish.mutate()}><FileCheck2 size={17} />Опублікувати</Button>}>{query.isLoading ? <Skeleton /> : query.isError || !query.data ? <ErrorState /> : <div className="detail-stack"><div><StatusBadge status={query.data.status} /><h3>{query.data.name}</h3><p className="privacy-note"><ShieldCheck size={17} />ACL перевірено під час цього відкриття.</p></div><section><h4>Версії</h4><div className="version-list">{query.data.versions.map((version) => <article key={version.id}><FileIcon size={20} /><span><strong>Версія {version.version}</strong><small>{version.changeSummary} · {formatDateTime(version.createdAt)}</small></span><a className="icon-button" aria-label="Завантажити" href={`/api/v1/files/${version.fileId}/download`}><Download size={17} /></a></article>)}</div></section></div>}</Drawer>
}

function KnowledgePage() {
  const { articleSlug } = useParams(); const navigate = useNavigate(); const { can } = useAuth(); const [search, setSearch] = useState('')
  const query = useQuery({ queryKey: ['knowledge', search], queryFn: () => api<{ items: ArticleList[] }>(`/knowledge/articles?search=${encodeURIComponent(search)}`) })
  return <div><PageHeader title="База знань" description="Інструкції, політики та матеріали для щоденної роботи" action={can('knowledge.manage') && <Link to="/admin/system?tab=directories" className="button button--secondary">Керувати матеріалами</Link>} /><div className="knowledge-layout"><Card className="knowledge-feature"><BookOpenCheck size={30} /><span className="eyebrow">Знання команди</span><h2>Знайдіть відповідь без зайвих запитів</h2><label className="search-field"><Search size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Введіть тему або ключове слово" /></label></Card><section className="article-grid">{query.isLoading ? <Skeleton rows={6} /> : query.isError ? <ErrorState /> : query.data?.items.map((item) => <Link to={`/knowledge/${item.slug}`} key={item.id}><span className="article-icon"><BookOpenCheck size={20} /></span><div><h3>{item.title}</h3><p>{item.changeSummary || 'Актуальна інструкція BERT CRM'}</p><small>Оновлено {formatDate(item.updatedAt)} · версія {item.version}</small></div></Link>)}</section></div>{articleSlug && <ArticleDrawer slug={articleSlug} onClose={() => navigate('/knowledge')} />}</div>
}

function ArticleDrawer({ slug, onClose }: { slug: string; onClose: () => void }) {
  const client = useQueryClient(); const query = useQuery({ queryKey: ['article', slug], queryFn: () => api<ArticleDetail>(`/knowledge/articles/${slug}`) })
  const ack = useMutation({ mutationFn: () => api(`/knowledge/articles/${slug}/acknowledge`, { method: 'POST', body: jsonBody({ expectedVersion: query.data?.version }) }), onSuccess: () => void client.invalidateQueries({ queryKey: ['article', slug] }) })
  return <Drawer title="Стаття" onClose={onClose} footer={query.data && !query.data.acknowledgement?.confirmedAt && <Button onClick={() => ack.mutate()}><Check size={17} />Підтвердити ознайомлення</Button>}>{query.isLoading ? <Skeleton /> : query.isError || !query.data?.currentVersion ? <ErrorState /> : <article className="article-detail"><span className="eyebrow">Версія {query.data.version}</span><h2>{query.data.currentVersion.title}</h2><p className="article-meta">Опубліковано {formatDateTime(query.data.currentVersion.publishedAt)}</p><div className="article-body">{query.data.currentVersion.body.split('\n').map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div>{query.data.acknowledgement?.confirmedAt && <p className="success-note"><Check size={17} />Ви ознайомилися {formatDateTime(query.data.acknowledgement.confirmedAt)}</p>}</article>}</Drawer>
}

function EmployeesPage() {
  const { employeeId } = useParams(); const navigate = useNavigate(); const [search, setSearch] = useState('')
  const query = useQuery({ queryKey: ['employees', search], queryFn: () => api<{ items: Employee[] }>(`/employees?search=${encodeURIComponent(search)}`) })
  return <div><PageHeader title="Працівники" description="Безпечний довідник людей у доступних компаніях" /><Card className="directory-card"><label className="search-field"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Ім’я, посада або нікнейм" /></label>{query.isLoading ? <Skeleton rows={6} /> : query.isError ? <ErrorState /> : query.data?.items.length ? <div className="employee-grid">{query.data.items.map((item) => <Link to={`/employees/${item.id}`} key={item.id}><Avatar size="lg" name={item.displayName} src={item.avatarAsset} /><span><strong>{item.displayName}</strong><small>{item.jobTitle}</small><em><i className={`presence presence--${item.presence.toLowerCase()}`} />{item.presence === 'AWAY' ? 'Відсутній' : 'Доступний'}</em></span></Link>)}</div> : <EmptyState title="Нікого не знайдено" description="Спробуйте інший запит." />}</Card>{employeeId && <EmployeeDrawer id={employeeId} onClose={() => navigate('/employees')} />}</div>
}

function EmployeeDrawer({ id, onClose }: { id: string; onClose: () => void }) { const query = useQuery({ queryKey: ['employee', id], queryFn: () => api<Employee>(`/employees/${id}`) }); return <Drawer title="Профіль працівника" onClose={onClose}>{query.isLoading ? <Skeleton /> : query.isError || !query.data ? <ErrorState /> : <div className="employee-detail"><Avatar size="lg" name={query.data.displayName} src={query.data.avatarAsset} /><h3>{query.data.displayName}</h3><p>{query.data.jobTitle} · {query.data.displayRole}</p><dl className="detail-grid"><div><dt>Часовий пояс</dt><dd>{query.data.timezone}</dd></div><div><dt>Керівник</dt><dd>{query.data.approver?.displayName ?? 'Не вказано'}</dd></div>{query.data.contactEmail && <div><dt>Контакт</dt><dd>{query.data.contactEmail}</dd></div>}</dl><section><h4>Найближча присутність</h4>{query.data.upcomingPresence?.length ? query.data.upcomingPresence.map((item) => <p key={item.startAt}><CalendarClock size={16} />{item.state} · {formatDate(item.startAt)} — {formatDate(item.endAt)}</p>) : <p className="muted">Особливих статусів немає.</p>}</section></div>}</Drawer> }

function AnalyticsPage() {
  interface Data { kpis: { taskCompletion: number; taskOverdue: number; requestTotal: number; activeLifecycle: number }; requests: Array<{ decisionStatus: string; _count: { id: number } }>; lifecycle: Array<{ processType: string; status: string; _count: { id: number }; _avg: { progress: number | null } }> }
  const query = useQuery({ queryKey: ['analytics'], queryFn: () => api<Data>('/analytics') })
  if (query.isLoading) return <><PageHeader title="Аналітика" /><Skeleton rows={7} /></>
  if (query.isError || !query.data) return <ErrorState />
  const max = Math.max(1, ...query.data.requests.map((item) => item._count.id))
  return <div><PageHeader title="Аналітика" description="Агреговані показники лише в межах доступного company scope" /><div className="kpi-grid"><Kpi icon={Check} label="Виконання задач" value={`${query.data.kpis.taskCompletion}%`} /><Kpi icon={CalendarClock} label="Прострочені" value={query.data.kpis.taskOverdue} /><Kpi icon={FileIcon} label="Усього заявок" value={query.data.kpis.requestTotal} /><Kpi icon={UsersRound} label="Активні процеси" value={query.data.kpis.activeLifecycle} /></div><div className="analytics-grid"><Card><h2>Рішення за заявками</h2><div className="bar-chart">{query.data.requests.map((item) => <div key={item.decisionStatus}><span>{item.decisionStatus}</span><i><b style={{ width: `${item._count.id / max * 100}%` }} /></i><strong>{item._count.id}</strong></div>)}</div></Card><Card><h2>Онбординг і офбординг</h2>{query.data.lifecycle.length ? query.data.lifecycle.map((item) => <article className="lifecycle-stat" key={`${item.processType}:${item.status}`}><BarChart3 size={19} /><span><strong>{item.processType}</strong><small>{item.status} · середній прогрес {Math.round(item._avg.progress ?? 0)}%</small></span><b>{item._count.id}</b></article>) : <EmptyState title="Процесів немає" description="Дані з’являться після запуску процесу." />}</Card></div></div>
}

function Kpi({ icon: Icon, label, value }: { icon: typeof Building2; label: string; value: string | number }) { return <Card className="kpi-card"><span><Icon size={20} /></span><div><strong>{value}</strong><small>{label}</small></div></Card> }
