import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { PageResult, RequestListItem } from '@bert-crm/contracts'
import { ArrowLeft, ArrowRight, CalendarRange, Check, CheckCircle2, Clock3, FileClock, Plus, ShieldCheck, UserRoundCheck, XCircle } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { Link, useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { api, idempotencyKey, jsonBody } from '../shared/api/client'
import { useAuth } from '../shared/auth/AuthProvider'
import { formatDate, formatDateTime } from '../shared/lib/format'
import { Avatar, Button, Card, Drawer, EmptyState, ErrorState, PageHeader, Skeleton, StatusBadge, Tabs } from '../shared/ui'

interface Employee { id: string; displayName: string; jobTitle: string; avatarAsset?: string | null }
interface RequestDetail { id: string; number: string; companyId: string; version: number; decisionStatus: string; executionStatus: string; currentApproverId?: string | null; author: Employee; currentApprover: { id: string; displayName: string } | null; privateFieldsHidden: boolean; snapshots: Array<{ id: string; version: number; safeSummary: string; valuesJson: string; createdAt: string }>; approvals: Array<{ id: string; state: string; comment?: string; decidedAt?: string; requestVersion: number }>; effects: Array<{ id: string; effectType: string; state: string }> }

export default function RequestsPage() {
  const { requestId } = useParams(); const location = useLocation(); const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const { can } = useAuth()
  const segment = params.get('tab') ?? 'mine'; const page = Number(params.get('page') ?? 1)
  const query = useQuery({ queryKey: ['requests', segment, page, params.get('company')], queryFn: () => api<PageResult<RequestListItem>>(`/requests?segment=${segment}&page=${page}&company=${params.get('company') ?? ''}`) })
  if (location.pathname === '/requests/new') return <AbsenceWizard onDone={(id) => navigate(`/requests/${id}`, { replace: true })} />
  return <div><PageHeader title="Заявки" description="Створення, погодження та прозорий стан виконання" action={can('requests.create') && <Link to="/requests/new?type=absence" className="button button--primary"><Plus size={17} />Нова заявка</Link>} />
    <Card className="list-card"><div className="list-toolbar"><Tabs value={segment} onChange={(value) => setParams((current) => { current.set('tab', value); current.delete('page'); return current })} items={[{ value: 'mine', label: 'Мої', count: segment === 'mine' ? query.data?.total : undefined }, ...(can('requests.approve') ? [{ value: 'approval', label: 'На погодження', count: segment === 'approval' ? query.data?.total : undefined }, { value: 'company', label: 'Доступні в компанії' }] : [])]} /></div>
      {query.isLoading ? <Skeleton rows={7} /> : query.isError ? <ErrorState onRetry={() => void query.refetch()} /> : query.data?.items.length ? <div className="responsive-table"><table><thead><tr><th>Заявка</th><th>Погоджувач</th><th>Оновлено</th><th>Рішення</th><th>Виконання</th></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id}><td><Link to={`/requests/${item.id}${location.search}`}><FileClock size={18} /><span><strong>{item.type}</strong><small>{item.number} · {item.safeSummary}</small></span></Link></td><td>{item.currentApprover?.displayName ?? '—'}</td><td>{formatDateTime(item.updatedAt)}</td><td><StatusBadge status={item.decisionStatus} /></td><td><StatusBadge status={item.executionStatus} /></td></tr>)}</tbody></table></div> : <EmptyState title="Заявок немає" description={segment === 'approval' ? 'Усі рішення опрацьовано.' : 'Створіть першу заявку — наприклад, на відпустку.'} />}
    </Card>{requestId && <RequestDrawer id={requestId} onClose={() => navigate(`/requests${location.search}`)} />}</div>
}

function AbsenceWizard({ onDone }: { onDone: (id: string) => void }) {
  const { user } = useAuth(); const navigate = useNavigate(); const [step, setStep] = useState(1); const [error, setError] = useState(''); const [values, setValues] = useState({ startDate: '', endDate: '', substituteId: '', privateHrComment: '' })
  const employees = useQuery({ queryKey: ['employees', 'absence'], queryFn: () => api<{ items: Employee[] }>('/employees') })
  const substitute = employees.data?.items.find((item) => item.id === values.substituteId)
  const workdays = useMemo(() => { if (!values.startDate || !values.endDate) return 0; let count = 0; const current = new Date(`${values.startDate}T12:00:00Z`); const end = new Date(`${values.endDate}T12:00:00Z`); while (current <= end) { if (![0, 6].includes(current.getUTCDay())) count += 1; current.setUTCDate(current.getUTCDate() + 1) } return count }, [values.startDate, values.endDate])
  function next(event: FormEvent) { event.preventDefault(); if (step === 1 && (!values.startDate || !values.endDate || values.endDate < values.startDate)) return setError('Перевірте період відсутності.'); if (step === 2 && !values.substituteId) return setError('Оберіть заміну.'); setError(''); setStep((value) => Math.min(value + 1, 3)) }
  async function submit() { setError(''); try { const result = await api<RequestDetail>('/requests/absence', { method: 'POST', headers: { 'idempotency-key': idempotencyKey('absence') }, body: jsonBody({ ...values, companyId: user?.primaryCompanyId }) }); onDone(result.id) } catch { setError('Не вдалося подати заявку. Можливо, для профілю не визначено погоджувача.') } }
  return <div className="wizard-page"><PageHeader title="Нова заявка" description="Відсутність · Відпустка" /><div className="stepper" aria-label="Кроки заявки">{['Період', 'Заміна', 'Перевірка'].map((label, index) => <span className={step >= index + 1 ? 'is-active' : ''} key={label}><i>{step > index + 1 ? <Check size={14} /> : index + 1}</i>{label}</span>)}</div><div className="wizard-layout"><Card className="wizard-card"><form onSubmit={next}>
    {step === 1 && <div className="wizard-step"><span className="step-icon"><CalendarRange /></span><h2>Коли вас не буде?</h2><p>Дати відображатимуться у календарі без приватної причини.</p><div className="date-pair"><label>Перший день<input type="date" value={values.startDate} onChange={(event) => setValues({ ...values, startDate: event.target.value })} required /></label><ArrowRight /><label>Останній день<input type="date" min={values.startDate} value={values.endDate} onChange={(event) => setValues({ ...values, endDate: event.target.value })} required /></label></div>{workdays > 0 && <div className="workday-note"><Clock3 size={17} /><strong>{workdays} робочих днів</strong><span>за стандартним п’ятиденним графіком</span></div>}</div>}
    {step === 2 && <div className="wizard-step"><span className="step-icon"><UserRoundCheck /></span><h2>Хто підстрахує?</h2><p>Оберіть колегу, який бачитиме лише безпечну інформацію про період заміни.</p><div className="people-picker">{employees.data?.items.filter((item) => item.id !== user?.id).map((item) => <label className={values.substituteId === item.id ? 'is-selected' : ''} key={item.id}><input type="radio" name="substitute" value={item.id} checked={values.substituteId === item.id} onChange={() => setValues({ ...values, substituteId: item.id })} /><Avatar name={item.displayName} src={item.avatarAsset} /><span><strong>{item.displayName}</strong><small>{item.jobTitle}</small></span><CheckCircle2 size={19} /></label>)}</div><label>Приватний коментар для HR <span className="optional">необов’язково</span><textarea rows={3} maxLength={1000} value={values.privateHrComment} onChange={(event) => setValues({ ...values, privateHrComment: event.target.value })} placeholder="Не потрапляє у календар, пошук чи повідомлення керівнику" /></label></div>}
    {step === 3 && <div className="wizard-step"><span className="step-icon"><ShieldCheck /></span><h2>Перевірте перед надсиланням</h2><div className="review-block"><div><span>Тип</span><strong>Відсутність · Відпустка</strong></div><div><span>Період</span><strong>{formatDate(values.startDate)} — {formatDate(values.endDate)} · {workdays} робочих днів</strong></div><div><span>Заміна</span><strong>{substitute?.displayName}</strong></div><div><span>Погодження</span><strong>Безпосередній керівник · SLA 2 дні</strong></div></div><p className="privacy-note"><ShieldCheck size={17} />Приватний HR-коментар зберігається окремо й зашифровано. Керівник не побачить його.</p></div>}
    {error && <div className="form-error" role="alert">{error}</div>}<div className="form-actions"><Button type="button" variant="secondary" onClick={() => step === 1 ? navigate('/requests') : setStep(step - 1)}><ArrowLeft size={17} />{step === 1 ? 'Скасувати' : 'Назад'}</Button>{step < 3 ? <Button>Далі <ArrowRight size={17} /></Button> : <Button type="button" onClick={() => void submit()}>Надіслати на погодження</Button>}</div>
  </form></Card><aside className="wizard-aside"><strong>Що станеться після погодження?</strong><ul><li><CalendarRange size={17} />Відсутність з’явиться у календарі</li><li><UserRoundCheck size={17} />Заміна отримає безпечне сповіщення</li><li><ShieldCheck size={17} />HR побачить дозволені деталі</li></ul></aside></div></div>
}

function RequestDrawer({ id, onClose }: { id: string; onClose: () => void }) {
  const { user, can } = useAuth(); const client = useQueryClient(); const [comment, setComment] = useState('')
  const query = useQuery({ queryKey: ['request', id], queryFn: () => api<RequestDetail>(`/requests/${id}`) })
  const decision = useMutation({ mutationFn: ({ action, version, comment: note }: { action: 'approve' | 'return' | 'reject'; version: number; comment?: string }) => api(`/requests/${id}/${action}`, { method: 'POST', headers: action === 'approve' ? { 'idempotency-key': idempotencyKey('approval') } : undefined, body: jsonBody({ expectedVersion: version, ...(note ? { comment: note } : {}) }) }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['request', id] }); void client.invalidateQueries({ queryKey: ['requests'] }); void client.invalidateQueries({ queryKey: ['dashboard'] }) } })
  const latest = query.data?.snapshots[0]; let values: { startAt?: string; endAt?: string; workdays?: number; substituteId?: string } = {}; try { values = latest ? JSON.parse(latest.valuesJson) as typeof values : {} } catch { /* safe fallback */ }
  const mayDecide = query.data?.decisionStatus === 'PENDING' && query.data.currentApproverId === user?.id && can('requests.approve')
  return <Drawer title={query.data?.number ?? 'Заявка'} onClose={onClose} footer={mayDecide && query.data ? <div className="decision-actions"><Button variant="secondary" onClick={() => { if (!comment.trim()) return; decision.mutate({ action: 'return', version: query.data.version, comment }) }}>Повернути</Button><Button variant="danger" onClick={() => { if (!comment.trim()) return; decision.mutate({ action: 'reject', version: query.data.version, comment }) }}><XCircle size={16} />Відхилити</Button><Button onClick={() => decision.mutate({ action: 'approve', version: query.data.version })}><Check size={16} />Погодити</Button></div> : undefined}>
    {query.isLoading ? <Skeleton rows={7} /> : query.isError || !query.data ? <ErrorState onRetry={() => void query.refetch()} /> : <div className="detail-stack"><div><StatusBadge status={query.data.decisionStatus} /><h3>{latest?.safeSummary ?? 'Заявка'}</h3><div className="request-author"><Avatar name={query.data.author.displayName} src={query.data.author.avatarAsset} /><span><strong>{query.data.author.displayName}</strong><small>{query.data.author.jobTitle}</small></span></div></div><dl className="detail-grid"><div><dt>Період</dt><dd>{values.startAt && values.endAt ? `${formatDate(values.startAt)} — ${formatDate(values.endAt)}` : '—'}</dd></div><div><dt>Робочих днів</dt><dd>{values.workdays ?? '—'}</dd></div><div><dt>Погоджувач</dt><dd>{query.data.currentApprover?.displayName ?? '—'}</dd></div><div><dt>Виконання</dt><dd><StatusBadge status={query.data.executionStatus} /></dd></div></dl>{query.data.privateFieldsHidden && <p className="privacy-note"><ShieldCheck size={17} />Приватні HR-поля приховано відповідно до вашого content scope.</p>}<section><h4>Історія рішень</h4><ol className="activity-timeline">{query.data.snapshots.map((item) => <li key={item.id}><i /><div><strong>Версія {item.version}</strong><p>{item.safeSummary}</p><small>{formatDateTime(item.createdAt)}</small></div></li>)}</ol></section>{mayDecide && <label>Коментар для повернення або відхилення<textarea rows={3} value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Обов’язковий для негативного рішення" /></label>}</div>}
  </Drawer>
}
