import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { SessionView } from '@bert-crm/contracts'
import { BellRing, Check, KeyRound, Laptop, LogOut, Save, ShieldCheck, Smartphone, UserRound } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { NavLink, useLocation } from 'react-router-dom'
import { api, jsonBody } from '../shared/api/client'
import { useAuth } from '../shared/auth/AuthProvider'
import { formatDateTime } from '../shared/lib/format'
import { Avatar, Button, Card, ErrorState, PageHeader, Skeleton } from '../shared/ui'

export default function SettingsPages() {
  const path = useLocation().pathname
  return <div><PageHeader title="Особисті налаштування" description="Профіль, сповіщення та захист вашого облікового запису" /><div className="settings-layout"><nav aria-label="Налаштування"><NavLink to="/settings/profile"><UserRound size={17} />Профіль</NavLink><NavLink to="/settings/notifications"><BellRing size={17} />Сповіщення</NavLink><NavLink to="/settings/security"><KeyRound size={17} />Безпека</NavLink><NavLink to="/settings/sessions"><Laptop size={17} />Сесії</NavLink></nav><section>{path.endsWith('/profile') ? <ProfileSettings /> : path.endsWith('/notifications') ? <NotificationSettings /> : path.endsWith('/security') ? <SecuritySettings /> : <SessionsSettings />}</section></div></div>
}

function ProfileSettings() {
  const { user, refresh } = useAuth(); const [saved, setSaved] = useState(false); const [error, setError] = useState('')
  if (!user) return null
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaved(false); setError(''); const data = new FormData(event.currentTarget); try { await api('/me/profile', { method: 'PATCH', body: jsonBody({ displayName: data.get('displayName'), jobTitle: data.get('jobTitle'), contactEmail: data.get('contactEmail') || null, timezone: data.get('timezone'), locale: data.get('locale') }) }); await refresh(); setSaved(true) } catch { setError('Не вдалося зберегти профіль.') } }
  return <Card className="settings-card"><header><Avatar size="lg" name={user.displayName} src={user.avatarAsset} /><div><h2>Профіль</h2><p>Дані, які колеги бачать у робочих процесах.</p></div></header><form className="entity-form" onSubmit={submit}><label>Ім’я<input name="displayName" defaultValue={user.displayName} required /></label><label>Нікнейм<input value={`@${user.username}`} disabled readOnly /><small>Змінює лише адміністратор</small></label><label>Посада<input name="jobTitle" defaultValue={user.jobTitle} /></label><label>Контактний email<input name="contactEmail" type="email" /></label><label>Часовий пояс<select name="timezone" defaultValue="Europe/Kyiv"><option>Europe/Kyiv</option><option>Europe/Warsaw</option><option>Europe/London</option></select></label><label>Мова<select name="locale" defaultValue="uk-UA"><option value="uk-UA">Українська</option><option value="en-US">English</option></select></label>{error && <div className="form-error span-2">{error}</div>}{saved && <p className="success-note span-2"><Check size={16} />Зміни збережено</p>}<div className="form-actions span-2"><Button><Save size={17} />Зберегти</Button></div></form></Card>
}

interface Preference { emailEnabled: boolean; inAppEnabled: boolean; digest: string; quietStart: string; quietEnd: string }
function NotificationSettings() {
  const query = useQuery({ queryKey: ['notification-preferences'], queryFn: () => api<Preference>('/me/notification-preferences') }); const client = useQueryClient()
  const save = useMutation({ mutationFn: (input: Preference) => api('/me/notification-preferences', { method: 'PATCH', body: jsonBody(input) }), onSuccess: () => void client.invalidateQueries({ queryKey: ['notification-preferences'] }) })
  if (query.isLoading) return <Card><Skeleton /></Card>; if (query.isError || !query.data) return <ErrorState />
  return <Card className="settings-card"><header><span className="settings-icon"><BellRing /></span><div><h2>Сповіщення</h2><p>Критичні security-події не можна вимкнути.</p></div></header><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); save.mutate({ emailEnabled: data.get('email') === 'on', inAppEnabled: true, digest: String(data.get('digest')), quietStart: String(data.get('quietStart')), quietEnd: String(data.get('quietEnd')) }) }} className="preference-form"><label><span><strong>У застосунку</strong><small>Задачі, погодження, згадки й безпека</small></span><input type="checkbox" checked readOnly /></label><label><span><strong>Email-дайджест</strong><small>Без приватного вмісту в темі листа</small></span><input type="checkbox" name="email" defaultChecked={query.data.emailEnabled} /></label><label><span><strong>Частота дайджесту</strong></span><select name="digest" defaultValue={query.data.digest}><option value="IMMEDIATE">Одразу</option><option value="DAILY">Щодня</option><option value="WEEKLY">Щотижня</option></select></label><div className="quiet-hours"><label>Тихий режим від<input type="time" name="quietStart" defaultValue={query.data.quietStart} /></label><label>до<input type="time" name="quietEnd" defaultValue={query.data.quietEnd} /></label></div><Button disabled={save.isPending}><Save size={17} />Зберегти</Button>{save.isSuccess && <p className="success-note"><Check size={16} />Збережено</p>}</form></Card>
}

function SecuritySettings() {
  const [saved, setSaved] = useState(false); const [error, setError] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setSaved(false); setError(''); try { await api('/auth/password', { method: 'POST', body: jsonBody({ currentPassword: data.get('currentPassword'), newPassword: data.get('newPassword'), confirmation: data.get('confirmation') }) }); event.currentTarget.reset(); setSaved(true) } catch { setError('Не вдалося змінити пароль. Перевірте поточний пароль і політику нового.') } }
  return <div className="settings-stack"><Card className="settings-card"><header><span className="settings-icon"><KeyRound /></span><div><h2>Змінити пароль</h2><p>Щонайменше 15 символів; без передбачуваних фраз і нікнейма.</p></div></header><form className="security-form" onSubmit={submit}><label>Поточний пароль<input name="currentPassword" type="password" required autoComplete="current-password" /></label><label>Новий пароль<input name="newPassword" type="password" minLength={15} required autoComplete="new-password" /></label><label>Повторіть новий пароль<input name="confirmation" type="password" minLength={15} required autoComplete="new-password" /></label>{error && <div className="form-error">{error}</div>}{saved && <p className="success-note"><Check size={16} />Пароль змінено, інші сесії завершено.</p>}<Button>Змінити пароль</Button></form></Card><Card className="security-summary"><ShieldCheck size={25} /><div><h3>Двофакторна автентифікація</h3><p>Керування 2FA і recovery codes потребує повторного підтвердження особи.</p></div><span>Захищено</span></Card></div>
}

function SessionsSettings() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ['sessions'], queryFn: () => api<SessionView[]>('/me/sessions') })
  const revoke = useMutation({ mutationFn: (id: string) => api(`/me/sessions/${id}`, { method: 'DELETE' }), onSuccess: () => void client.invalidateQueries({ queryKey: ['sessions'] }) })
  const others = useMutation({ mutationFn: () => api('/me/sessions/revoke-others', { method: 'POST' }), onSuccess: () => void client.invalidateQueries({ queryKey: ['sessions'] }) })
  return <Card className="settings-card"><header><span className="settings-icon"><Laptop /></span><div><h2>Активні сесії</h2><p>Завершуйте доступ на пристроях, які більше не використовуєте.</p></div></header>{query.isLoading ? <Skeleton /> : query.isError ? <ErrorState /> : <div className="session-list">{query.data?.map((session) => <article key={session.id}><span>{session.deviceLabel.toLowerCase().includes('mobile') ? <Smartphone /> : <Laptop />}</span><div><strong>{session.deviceLabel}</strong><small>{session.current ? 'Цей пристрій' : `Остання активність ${formatDateTime(session.lastSeenAt)}`}</small></div>{session.current ? <b>Поточна</b> : <Button variant="ghost" onClick={() => revoke.mutate(session.id)}><LogOut size={16} />Завершити</Button>}</article>)}</div>}<footer><Button variant="secondary" onClick={() => others.mutate()} disabled={others.isPending}>Завершити всі інші сесії</Button></footer></Card>
}
